# Generated by Django 5.1.15 on 2026-01-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0027_calendardate_grouped_classes'),
    ]

    operations = [
    ]
