# Generated by Django 5.1.15 on 2026-01-12 06:25
# PHASE 1 OPTIMIZATION: Convert status fields from CharField to SmallIntegerField

from django.db import migrations, models


def safe_add_indexes(apps, schema_editor):
    """Safely add indexes, skipping those that already exist"""
    with schema_editor.connection.cursor() as cursor:
        indexes_to_add = [
            ('enroll_active_sch_idx', 'CREATE INDEX IF NOT EXISTS enroll_active_sch_idx ON class_enrollment(is_active, school_id)'),
            ('attend_status_date_idx', 'CREATE INDEX IF NOT EXISTS attend_status_date_idx ON class_attendance(status, marked_at)'),
            ('attend_stud_date_idx', 'CREATE INDEX IF NOT EXISTS attend_stud_date_idx ON class_attendance(student_id, marked_at)'),
            ('attend_cls_date_idx', 'CREATE INDEX IF NOT EXISTS attend_cls_date_idx ON class_attendance(class_section_id, marked_at)'),
            ('attend_sch_date_idx', 'CREATE INDEX IF NOT EXISTS attend_sch_date_idx ON class_attendance(school_id, marked_at)'),
            ('asess_sess_stat_idx', 'CREATE INDEX IF NOT EXISTS asess_sess_stat_idx ON class_actualsession(planned_session_id, status)'),
            ('asess_date_stat_idx', 'CREATE INDEX IF NOT EXISTS asess_date_stat_idx ON class_actualsession(date, status)'),
            ('asess_facil_date_idx', 'CREATE INDEX IF NOT EXISTS asess_facil_date_idx ON class_actualsession(facilitator_id, date)'),
            ('asess_stat_date_idx', 'CREATE INDEX IF NOT EXISTS asess_stat_date_idx ON class_actualsession(status, date)'),
            ('caldate_cal_date_idx', 'CREATE INDEX IF NOT EXISTS caldate_cal_date_idx ON class_calendardate(calendar_id, date)'),
            ('caldate_type_date_idx', 'CREATE INDEX IF NOT EXISTS caldate_type_date_idx ON class_calendardate(date_type, date)'),
            ('caldate_sch_date_idx', 'CREATE INDEX IF NOT EXISTS caldate_sch_date_idx ON class_calendardate(school_id, date)'),
            ('perf_stud_subj_idx', 'CREATE INDEX IF NOT EXISTS perf_stud_subj_idx ON class_studentperformance(student_id, subject)'),
            ('perf_cls_subj_idx', 'CREATE INDEX IF NOT EXISTS perf_cls_subj_idx ON class_studentperformance(class_section_id, subject)'),
            ('facsch_active_sch_idx', 'CREATE INDEX IF NOT EXISTS facsch_active_sch_idx ON class_facilitatorschool(is_active, school_id)'),
            ('facsch_facil_active_idx', 'CREATE INDEX IF NOT EXISTS facsch_facil_active_idx ON class_facilitatorschool(facilitator_id, is_active)'),
            ('suslog_sess_facil_idx', 'CREATE INDEX IF NOT EXISTS suslog_sess_facil_idx ON class_sessionusagelog(session_id, facilitator_id)'),
            ('suslog_facil_ts_idx', 'CREATE INDEX IF NOT EXISTS suslog_facil_ts_idx ON class_sessionusagelog(facilitator_id, access_timestamp)'),
            ('culog_curr_facil_idx', 'CREATE INDEX IF NOT EXISTS culog_curr_facil_idx ON class_curriculumusagelog(curriculum_session_id, facilitator_id)'),
            ('culog_facil_ts_idx', 'CREATE INDEX IF NOT EXISTS culog_facil_ts_idx ON class_curriculumusagelog(facilitator_id, access_timestamp)'),
        ]
        
        for idx_name, sql in indexes_to_add:
            try:
                cursor.execute(sql)
            except Exception as e:
                # Index already exists or other error - continue
                pass


def reverse_safe_add_indexes(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0028_grouped_session_support'),
    ]

    operations = [
        # Step 1: Add new denormalized fields to Attendance
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.student_id', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_section_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.class_section_id', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.school_id', null=True),
        ),
        
        # Step 2: Alter field types from CharField to SmallIntegerField
        migrations.AlterField(
            model_name='actualsession',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Conducted'), (2, 'Holiday'), (3, 'Cancelled')], default=1, help_text='Session status: 1=Conducted, 2=Holiday, 3=Cancelled'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Leave')], default=1, help_text='Attendance status: 1=Present, 2=Absent, 3=Leave'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='date_type',
            field=models.SmallIntegerField(choices=[(1, 'Planned Session'), (2, 'Holiday / No Session'), (3, 'Office Work / Task')], default=1, help_text='Type: 1=Session, 2=Holiday, 3=Office Work'),
        ),
        migrations.AlterField(
            model_name='curriculumsession',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=1, help_text='Status: 1=Draft, 2=Published, 3=Archived'),
        ),
        
        # Step 3: Safely add all indexes
        migrations.RunPython(safe_add_indexes, reverse_safe_add_indexes),
    ]
