# Generated by Django 5.1.15 on 2026-02-02 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0044_groupedsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCutoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passing_score', models.IntegerField(default=40, help_text='Minimum score to pass (0-100)')),
                ('excellent_score', models.IntegerField(default=80, help_text='Score for excellent performance (0-100)')),
                ('good_score', models.IntegerField(default=60, help_text='Score for good performance (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Performance Cutoffs',
            },
        ),
        migrations.CreateModel(
            name='StudentPerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_score', models.FloatField(default=0, help_text='Average score across all subjects')),
                ('total_subjects', models.IntegerField(default=0)),
                ('passed_subjects', models.IntegerField(default=0)),
                ('failed_subjects', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, help_text='Rank in class', null=True)),
                ('is_passed', models.BooleanField(default=False, help_text='Overall pass/fail status')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentperformance',
            options={'ordering': ['-recorded_date']},
        ),
        migrations.RenameField(
            model_name='studentperformance',
            old_name='created_at',
            new_name='recorded_date',
        ),
        migrations.RenameIndex(
            model_name='groupedsession',
            new_name='class_group_grouped_8657b2_idx',
            old_name='class_group_grouped_idx',
        ),
        migrations.AlterUniqueTogether(
            name='plannedsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='grade',
            field=models.CharField(choices=[('A', 'Excellent (80-100)'), ('B', 'Good (60-79)'), ('C', 'Average (40-59)'), ('F', 'Failed (0-39)')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='remarks',
            field=models.TextField(blank=True, help_text='Teacher remarks'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actualsession',
            name='facilitator_attendance',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('', 'Not Marked')], default='', help_text='Facilitator attendance status', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='class.classsection'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='score',
            field=models.IntegerField(help_text='Score out of 100'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='class.student'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['planned_session', 'status'], name='asess_sess_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['date', 'status'], name='asess_date_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['facilitator', 'date'], name='asess_facil_date_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['status', 'date'], name='asess_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'marked_at'], name='attend_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id', 'marked_at'], name='attend_stud_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_section_id', 'marked_at'], name='attend_cls_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school_id', 'marked_at'], name='attend_sch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'date'], name='caldate_cal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['date_type', 'date'], name='caldate_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['school', 'date'], name='caldate_sch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumusagelog',
            index=models.Index(fields=['curriculum_session', 'facilitator'], name='culog_curr_facil_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumusagelog',
            index=models.Index(fields=['facilitator', 'access_timestamp'], name='culog_facil_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active', 'school'], name='enroll_active_sch_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='enroll_stud_active_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitatorschool',
            index=models.Index(fields=['is_active', 'school'], name='facsch_active_sch_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitatorschool',
            index=models.Index(fields=['facilitator', 'is_active'], name='facsch_facil_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionusagelog',
            index=models.Index(fields=['session', 'facilitator'], name='suslog_sess_facil_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionusagelog',
            index=models.Index(fields=['facilitator', 'access_timestamp'], name='suslog_facil_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=models.UniqueConstraint(condition=models.Q(('grouped_session_id__isnull', True)), fields=('class_section', 'day_number'), name='unique_planned_session_non_grouped'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=models.UniqueConstraint(condition=models.Q(('grouped_session_id__isnull', False)), fields=('class_section', 'day_number', 'grouped_session_id'), name='unique_planned_session_grouped'),
        ),
        migrations.AddField(
            model_name='performancecutoff',
            name='class_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_cutoff', to='class.classsection'),
        ),
        migrations.AddField(
            model_name='studentperformancesummary',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='class.classsection'),
        ),
        migrations.AddField(
            model_name='studentperformancesummary',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summary', to='class.student'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='class.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together={('student', 'class_section', 'subject')},
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['student', 'subject'], name='perf_stud_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['class_section', 'subject'], name='perf_cls_subj_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentperformancesummary',
            unique_together={('student', 'class_section')},
        ),
    ]
