# Generated by Django 5.1.15 on 2026-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0046_alter_facilitatortask_actual_session_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualsession',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Conducted'), (2, 'Holiday'), (3, 'Cancelled')], default=1, help_text='Session status: 1=Conducted, 2=Holiday, 3=Cancelled'),
        ),
    ]
