# Generated by Django 5.1.15 on 2026-02-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0047_attendance_observation_notes'),
        ('class', '0048_remove_legacy_feedback_fields'),
    ]

    operations = [
    ]
