# Generated by Django 5.1.15 on 2026-02-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0049_merge_20260209_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='feedback_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
