# Generated by Django 5.1.15 on 2026-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0050_alter_sessionfeedback_feedback_date_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='areas_for_improvement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='what_went_well',
            field=models.TextField(blank=True),
        ),
    ]
