# Generated by Django 5.1.15 on 2026-02-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0048_student_growth_models'),
        ('class', '0051_make_sessionfeedback_fields_optional'),
    ]

    operations = [
    ]
