# Generated by Django 5.1.15 on 2026-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0052_merge_20260221_2220'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['grouped_session_id', 'day_number'], name='class_plann_grouped_6e7056_idx'),
        ),
    ]
