# Generated by Django 5.1.15 on 2026-02-26 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0053_add_grouped_session_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the guardian', max_length=100)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('cousin', 'Cousin'), ('other', 'Other')], help_text='Relation to the student', max_length=50)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('connection_notes', models.TextField(blank=True, help_text='Additional notes about connection (e.g., Primary contact, Emergency contact)')),
                ('attachment_q1', models.BooleanField(default=False, help_text='Student shows strong emotional bond with this guardian')),
                ('attachment_q2', models.BooleanField(default=False, help_text='Student seeks comfort/support from this guardian')),
                ('attachment_q3', models.BooleanField(default=False, help_text="This guardian is actively involved in student's education")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student this guardian is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='class.student')),
            ],
            options={
                'verbose_name': 'Student Guardian',
                'verbose_name_plural': 'Student Guardians',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='class_stude_student_22b5c8_idx')],
            },
        ),
    ]
